language: node_js

node_js:
  - 10
  - 12
  - 13

script:
  - npm run lint
  - npm run test

deploy:
  provider: npm
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
